/**
 * Authentication primitives for the team server.
 *
 * Three concepts live here:
 *
 *  1. **Enrollment PINs.** 6-character codes from a reduced alphabet
 *     (`A-Z2-9`, dropping `0/1/I/O` so handwritten / shouted PINs don't
 *     get misread). Generated by an admin (or by the first-launch
 *     bootstrap), single-use, optionally time-bound. Burning a PIN
 *     mints a device row + bearer token.
 *
 *  2. **Bearer tokens.** 256 bits of `crypto.randomBytes`, base64url-
 *     encoded. The token in plain form ONLY exists in memory during
 *     enrollment and in the client's local config; the database
 *     stores an argon2id hash so a DB leak doesn't immediately
 *     impersonate every device. Comparing on auth uses argon2.verify
 *     across the candidate devices for the token's leading prefix
 *     (cheap pre-filter so we don't do N argon2 hashes per request).
 *
 *  3. **Fastify auth hook.** `requireDevice` is a `preHandler` that
 *     reads the `Authorization: Bearer <token>` header, looks up the
 *     device + member, attaches `request.member` / `request.device`,
 *     and bumps `lastSeenAt`. Returns 401 on missing / invalid token.
 *     A second hook, `requireAdmin`, layers the role check on top.
 */

import crypto from 'node:crypto'
import argon2 from 'argon2'
import type { FastifyReply, FastifyRequest } from 'fastify'
import {
  getDb,
  EMPTY_CAPABILITIES,
  parseCapabilities,
  parseAllowedProjectIds,
  type Role,
  type MemberCapabilities,
} from './db.js'

// Reduced-confusion alphabet: A-Z + 2-9, no 0/1/I/O. 32 chars × 6 digits
// = ~10^9 keyspace, plenty for a single team.
const PIN_ALPHABET = 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789'
const PIN_LENGTH = 6

/**
 * Cryptographically-random PIN of length {@link PIN_LENGTH}. Uses
 * rejection sampling against a 256-element byte buffer so the
 * distribution stays uniform regardless of the alphabet size.
 */
export function generatePin(): string {
  const out: string[] = []
  while (out.length < PIN_LENGTH) {
    const buf = crypto.randomBytes(PIN_LENGTH * 2)
    for (let i = 0; i < buf.length && out.length < PIN_LENGTH; i++) {
      const v = buf[i]
      // Drop bytes that would bias the alphabet (rejection sampling).
      if (v >= 256 - (256 % PIN_ALPHABET.length)) continue
      out.push(PIN_ALPHABET[v % PIN_ALPHABET.length])
    }
  }
  return out.join('')
}

/** 256-bit token, base64url. No padding, URL-safe, no shell-escape pain. */
export function generateToken(): string {
  return crypto.randomBytes(32).toString('base64url')
}

/**
 * Hash a token for storage. argon2id with conservative defaults; tokens
 * are random 256-bit values so we don't need brute-force-resistant
 * parameters — we use argon2 mostly to defend against DB-leak replay.
 */
export function hashToken(token: string): Promise<string> {
  return argon2.hash(token, { type: argon2.argon2id })
}

/**
 * Verify a candidate token against a stored hash. Returns false on
 * any error (verify throws on malformed input).
 */
export async function verifyToken(stored: string, candidate: string): Promise<boolean> {
  try {
    return await argon2.verify(stored, candidate)
  } catch {
    return false
  }
}

// ── PIN lifecycle ────────────────────────────────────────────────────

const DEFAULT_PIN_TTL_MS = 24 * 60 * 60 * 1000 // 24h

export interface IssuedPin {
  code: string
  role: Role
  expiresAt: number | null
  capabilities: MemberCapabilities
  allowedProjectIds: number[]
  autoOpenProjectId: number | null
}

/**
 * Issue a new PIN. The caller supplies the role to bake in and any
 * optional pre-fill (display name / GitHub username + capabilities),
 * which become defaults when the PIN gets consumed.
 *
 * `createdBy` is the issuing admin's member id, or null for the
 * bootstrap setup-PIN (no admin exists yet at that point).
 *
 * Capabilities default to `EMPTY_CAPABILITIES` — admin must opt-in to
 * each home-screen card. The exception is the bootstrap setup-PIN
 * (createdBy=null), which is hardcoded to all-on so the first admin
 * isn't locked out of their own server.
 */
export function issuePin(args: {
  role: Role
  displayName?: string | null
  githubUsername?: string | null
  createdBy: number | null
  ttlMs?: number | null
  capabilities?: MemberCapabilities
  allowedProjectIds?: number[]
  autoOpenProjectId?: number | null
}): IssuedPin {
  const now = Date.now()
  const ttl = args.ttlMs === undefined ? DEFAULT_PIN_TTL_MS : args.ttlMs
  const expiresAt = ttl === null ? null : now + ttl

  // Bootstrap setup-PIN: no admin exists yet, so this PIN is destined
  // to mint the first admin device. Hardcode all caps on so they don't
  // start with a useless install.
  const isBootstrap = args.createdBy === null
  const capabilities: MemberCapabilities = args.capabilities ?? (
    isBootstrap
      ? { createProject: true, browseTeamProjects: true, openProject: true, manufacturingView: true }
      : { ...EMPTY_CAPABILITIES }
  )
  const allowedProjectIds = args.allowedProjectIds ?? []
  const autoOpenProjectId = args.autoOpenProjectId ?? null

  // Loop on the very rare PRIMARY-KEY collision. We're not relying on
  // luck — at 6 chars × 32-letter alphabet that's ~10^9 keyspace, and
  // we only ever have a handful of PINs outstanding.
  for (let attempt = 0; attempt < 8; attempt++) {
    const code = generatePin()
    try {
      getDb().prepare(
        `INSERT INTO pins (code, role, displayName, githubUsername, expiresAt, createdBy, createdAt,
                           capabilities, allowedProjectIds, autoOpenProjectId)
         VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`
      ).run(
        code,
        args.role,
        args.displayName ?? null,
        args.githubUsername ?? null,
        expiresAt,
        args.createdBy,
        now,
        JSON.stringify(capabilities),
        JSON.stringify(allowedProjectIds),
        autoOpenProjectId,
      )
      return { code, role: args.role, expiresAt, capabilities, allowedProjectIds, autoOpenProjectId }
    } catch (err) {
      // SQLITE_CONSTRAINT_PRIMARYKEY — try a different code.
      if ((err as { code?: string }).code === 'SQLITE_CONSTRAINT_PRIMARYKEY') continue
      throw err
    }
  }
  throw new Error('PIN generation collided 8 times in a row — RNG broken?')
}

export interface PinRecord {
  code: string
  role: Role
  displayName: string | null
  githubUsername: string | null
  expiresAt: number | null
  consumedAt: number | null
  createdBy: number | null
  createdAt: number
  /** JSON-encoded MemberCapabilities. Use parseCapabilities() to read. */
  capabilities: string | null
  /** JSON-encoded number[]. Use parseAllowedProjectIds() to read. */
  allowedProjectIds: string | null
  autoOpenProjectId: number | null
}

/** Convenience: hydrate a raw PinRecord into structured caps + allowlist. */
export function pinCapabilities(pin: PinRecord): {
  capabilities: MemberCapabilities
  allowedProjectIds: number[]
  autoOpenProjectId: number | null
} {
  return {
    capabilities: parseCapabilities(pin.capabilities),
    allowedProjectIds: parseAllowedProjectIds(pin.allowedProjectIds),
    autoOpenProjectId: pin.autoOpenProjectId,
  }
}

/** Look up a PIN. Does NOT consume it. Returns null if unknown. */
export function findPin(code: string): PinRecord | null {
  const row = getDb()
    .prepare(`SELECT * FROM pins WHERE code = ?`)
    .get(code.toUpperCase()) as PinRecord | undefined
  return row ?? null
}

/**
 * Atomically consume a PIN. Returns the freshly-locked PIN row, or
 * null if the PIN is unknown / already consumed / expired. Callers
 * proceed to create a member + device only when this succeeds.
 *
 * The UPDATE … WHERE consumedAt IS NULL ensures two simultaneous
 * enrolment attempts with the same code can't both win.
 */
export function consumePin(code: string): PinRecord | null {
  const normalized = code.toUpperCase()
  const now = Date.now()
  const result = getDb().prepare(
    `UPDATE pins SET consumedAt = ?
     WHERE code = ? AND consumedAt IS NULL
       AND (expiresAt IS NULL OR expiresAt > ?)`
  ).run(now, normalized, now)
  if (result.changes === 0) return null
  return findPin(normalized)
}

/** Revoke an unconsumed PIN. No-op for already-consumed ones. */
export function revokePin(code: string): boolean {
  const result = getDb().prepare(
    `DELETE FROM pins WHERE code = ? AND consumedAt IS NULL`
  ).run(code.toUpperCase())
  return result.changes > 0
}

// ── Device + bearer middleware ───────────────────────────────────────

export interface AuthedMember {
  id: number
  displayName: string
  githubUsername: string | null
  role: Role
  status: 'active' | 'inactive'
  capabilities: MemberCapabilities
  allowedProjectIds: number[]
  autoOpenProjectId: number | null
}

export interface AuthedDevice {
  id: number
  memberId: number
  label: string
}

declare module 'fastify' {
  interface FastifyRequest {
    member?: AuthedMember
    device?: AuthedDevice
  }
}

/**
 * Look up which device owns a given token. Walks every device row and
 * argon2-verifies the candidate; with ≤a few hundred devices per team
 * that's well under a millisecond worst-case, and we avoid storing
 * tokens themselves (only hashes) so a DB leak isn't immediate
 * impersonation.
 *
 * If the team grows past ~1000 devices we'd add a short non-secret
 * prefix index on each token to filter candidates first — for now,
 * the brute walk is fine.
 */
async function findDeviceByToken(token: string): Promise<{
  device: AuthedDevice
  member: AuthedMember
} | null> {
  const rows = getDb().prepare(
    `SELECT d.id AS dId, d.memberId, d.label, d.tokenHash,
            m.id AS mId, m.displayName, m.githubUsername, m.role, m.status,
            m.capabilities, m.allowedProjectIds, m.autoOpenProjectId
       FROM devices d
       JOIN members m ON m.id = d.memberId
      WHERE m.status = 'active'`
  ).all() as Array<{
    dId: number
    memberId: number
    label: string
    tokenHash: string
    mId: number
    displayName: string
    githubUsername: string | null
    role: Role
    status: 'active' | 'inactive'
    capabilities: string | null
    allowedProjectIds: string | null
    autoOpenProjectId: number | null
  }>

  for (const row of rows) {
    if (await verifyToken(row.tokenHash, token)) {
      return {
        device: { id: row.dId, memberId: row.memberId, label: row.label },
        member: {
          id: row.mId,
          displayName: row.displayName,
          githubUsername: row.githubUsername,
          role: row.role,
          status: row.status,
          capabilities: parseCapabilities(row.capabilities),
          allowedProjectIds: parseAllowedProjectIds(row.allowedProjectIds),
          autoOpenProjectId: row.autoOpenProjectId,
        },
      }
    }
  }
  return null
}

/**
 * Fastify preHandler. Reads `Authorization: Bearer <token>`, looks up
 * the device, attaches member + device to the request, and bumps
 * `lastSeenAt`. Replies 401 on any failure path.
 */
export async function requireDevice(
  req: FastifyRequest,
  reply: FastifyReply,
): Promise<void> {
  const header = req.headers['authorization']
  if (!header || Array.isArray(header) || !header.startsWith('Bearer ')) {
    await reply.code(401).send({ error: 'Missing bearer token' })
    return
  }
  const token = header.slice(7).trim()
  if (!token) {
    await reply.code(401).send({ error: 'Empty bearer token' })
    return
  }
  const hit = await findDeviceByToken(token)
  if (!hit) {
    await reply.code(401).send({ error: 'Invalid token' })
    return
  }
  req.member = hit.member
  req.device = hit.device
  getDb().prepare(`UPDATE devices SET lastSeenAt = ? WHERE id = ?`)
    .run(Date.now(), hit.device.id)
}

/**
 * Layered on top of {@link requireDevice}; ensures the authenticated
 * member has role='admin'. Mentors / students hit 403 here.
 */
export async function requireAdmin(
  req: FastifyRequest,
  reply: FastifyReply,
): Promise<void> {
  await requireDevice(req, reply)
  if (reply.sent) return
  if (req.member?.role !== 'admin') {
    await reply.code(403).send({ error: 'Admin role required' })
  }
}
